/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebaframe;

import Inventario.Inventario;
import javax.swing.JOptionPane;
import trabajoprogramacion.LeerInfo;

/**
 *
 * @author AAron
 */
public class Rivales extends javax.swing.JFrame {

    /**
     * Creates new form Rivales
     */
    public Rivales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotonAjax = new javax.swing.JButton();
        BotonArchimago = new javax.swing.JButton();
        BotonCancerbero = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescripRivales = new javax.swing.JTextArea();
        imgRivales = new javax.swing.JLabel();
        alabatalla = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaframe/rivales.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Vijaya", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("PREPÁRATE PARA ENFRENTARTE A UNO DE ESTOS RIVALES!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 560, 70));

        BotonAjax.setBackground(new java.awt.Color(255, 0, 0));
        BotonAjax.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        BotonAjax.setText("AJAX");
        BotonAjax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAjaxActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAjax, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 30));

        BotonArchimago.setBackground(new java.awt.Color(255, 0, 0));
        BotonArchimago.setFont(new java.awt.Font("Vijaya", 1, 18)); // NOI18N
        BotonArchimago.setText("ARCHIMAGO RAYX");
        BotonArchimago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonArchimagoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonArchimago, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 170, 30));

        BotonCancerbero.setBackground(new java.awt.Color(255, 0, 0));
        BotonCancerbero.setFont(new java.awt.Font("Vijaya", 1, 22)); // NOI18N
        BotonCancerbero.setText("CANCERBERO");
        BotonCancerbero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancerberoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonCancerbero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 170, 30));

        DescripRivales.setBackground(new java.awt.Color(0, 0, 0));
        DescripRivales.setColumns(20);
        DescripRivales.setForeground(new java.awt.Color(255, 255, 255));
        DescripRivales.setRows(5);
        jScrollPane1.setViewportView(DescripRivales);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 240, 100));
        getContentPane().add(imgRivales, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 250, 130));

        alabatalla.setBackground(new java.awt.Color(255, 0, 0));
        alabatalla.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        alabatalla.setText("A LA BATALLA");
        alabatalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alabatallaActionPerformed(evt);
            }
        });
        getContentPane().add(alabatalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 190, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaframe/rivales.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAjaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAjaxActionPerformed
        imgRivales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ajax.jpg")));
        DescripRivales.setText("AJAX:\nSALUD=350\nMANA=200\nDAÑO FISICO=13\nDAÑO MAGICO=0");
    }//GEN-LAST:event_BotonAjaxActionPerformed

    private void BotonArchimagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonArchimagoActionPerformed
     imgRivales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/archimago.jpg")));
        DescripRivales.setText("ARCHIMAGO RAYX:\nSALUD=250\nMANA=450\nDAÑO FISICO=6\nDAÑO MAGICO=12");
    }//GEN-LAST:event_BotonArchimagoActionPerformed

    private void BotonCancerberoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancerberoActionPerformed
        imgRivales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancerbero.jpg")));
        DescripRivales.setText("CANCERBERO:\nSALUD=320\nMANA=320\nDAÑO FISICO=10\nDAÑO MAGICO=8");
    }//GEN-LAST:event_BotonCancerberoActionPerformed

    private void alabatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alabatallaActionPerformed
         
       Personaje.Batalla prueba = new Personaje.Batalla();
        prueba.comenzarBatalla();
      
      
         
              
             
    }//GEN-LAST:event_alabatallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rivales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rivales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rivales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rivales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rivales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAjax;
    private javax.swing.JButton BotonArchimago;
    private javax.swing.JButton BotonCancerbero;
    private javax.swing.JTextArea DescripRivales;
    private javax.swing.JButton alabatalla;
    private javax.swing.JLabel imgRivales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
