/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebaframe;

/**
 *
 * @author AAron
 */
public class seleccionarCampeon extends javax.swing.JFrame {

    /**
     * Creates new form seleccionarCampeon
     */
    public seleccionarCampeon() {
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BotonGuerrero = new javax.swing.JButton();
        BotonArquero = new javax.swing.JButton();
        botonMago = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        imgCampeon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(572, 429));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Vijaya", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("INFORMACIÓN DE LOS CAMPEONES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 460, 60));

        jButton1.setFont(new java.awt.Font("Vijaya", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("CONTINUAR");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 190, 40));

        BotonGuerrero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaframe/icon_guerrero.jpg"))); // NOI18N
        BotonGuerrero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuerreroActionPerformed(evt);
            }
        });
        getContentPane().add(BotonGuerrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 128, 128));

        BotonArquero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaframe/icon_arquero.jpg"))); // NOI18N
        BotonArquero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonArqueroActionPerformed(evt);
            }
        });
        getContentPane().add(BotonArquero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 128, 128));

        botonMago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaframe/icon_mago.png"))); // NOI18N
        botonMago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMagoActionPerformed(evt);
            }
        });
        getContentPane().add(botonMago, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 128, 128));

        description.setColumns(20);
        description.setFont(new java.awt.Font("Vijaya", 0, 20)); // NOI18N
        description.setForeground(new java.awt.Color(204, 0, 0));
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 180, 130));
        getContentPane().add(imgCampeon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 180, 130));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaframe/seleccioncampeon_1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               Rivales descripR = new Rivales();
               descripR.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonMagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMagoActionPerformed
        imgCampeon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/maga.jpg")));
        description.setText("MAGO:\nSALUD=400\nMANA=500\nDAÑO FISICO=7\nDAÑO MAGICO=12");
    }//GEN-LAST:event_botonMagoActionPerformed

    private void BotonArqueroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonArqueroActionPerformed
         imgCampeon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arquero.jpg")));
         description.setText("ARQUERO:\nSALUD=500\nMANA=300\nDAÑO FISICO=10\nDAÑO MAGICO=8");
    }//GEN-LAST:event_BotonArqueroActionPerformed

    private void BotonGuerreroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuerreroActionPerformed
          imgCampeon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guerrero.jpg")));
          description.setText("GUERRERO:\nSALUD=500\nMANA=300\nDAÑO FISICO=10\nDAÑO MAGICO=0");
    }//GEN-LAST:event_BotonGuerreroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seleccionarCampeon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seleccionarCampeon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seleccionarCampeon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seleccionarCampeon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seleccionarCampeon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonArquero;
    private javax.swing.JButton BotonGuerrero;
    private javax.swing.JButton botonMago;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel imgCampeon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
